# Generated by Django 2.1.7 on 2019-05-04 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20180930_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='text',
            new_name='txt',
        ),
    ]
